### ISSUE TITLE
Unnecessary imports?

### ISSUE THREAD

**Issue by Lithimlin** [chaosfissure/Namegen#1]
https://github.com/chaosfissure/Namegen/blob/206b723ff63f6efcea3e37689b9388e385aae43f/namegen.py#L4
Isn't it unnecessary to import `time` and `os`?

**Comment by chaosfissure** [comment]
That would indeed appear to be the case.  Not to mention that `time` is imported twice, for some reason XD It's probably a remnant I didn't totally expunge of autosaving generated names to a file to prevent duplicates from showing up after multiple runs.

Having said that, I've been making quite a few changes to this script, but my personal work these days lands in local version control rather than here. I'd be more inclined to update to the version I've been working with, which indeed would resolve these particular issues, but also is overhauled compared to what is seen here and requires Python 3.

Are you particularly interested in using this in some capacity?

**Comment by Lithimlin** [comment]
I've simply stumbled upon this code in search for a Markov Word Generator in Python.
I've tried translating [some Coffee code](https://github.com/SyntaxColoring/Markov-Word-Generator/blob/gh-pages/markov.coffee), so far without success as I don't know Coffee.
I'd be interested though in taking a look at your current version of this script. Maybe it can help me as well.

**Comment by chaosfissure** [comment]
Are you looking to understand how one of these works?  It's fairly straightforward to code one of these up once you know what they do / how they work, and I'd be happy to explain how I approached my specific implementation of this if the comments aren't clear enough at describing them.

Additionally, I've updated the repository with the changes I've made in the past two years.  Since the changes you've proposed are not present in the new version, I hope you don't mind me closing this particular issue.
